### ISSUE TITLE
Endgame trainers have no pokemon or barely any Pokemon in XD[BUG]

### ISSUE THREAD

**Issue by TheWrathAbove** [rotobash/pokemon-ngc-rando#34] opened 2022-05-15 17:26 UTC
Up until the fight with Snattle at Citidark Isle, everything was fine. At which point he had no pokemon, the battle with Ardos following him had no Pokemon, and after that, the fight with Gorgan only had a Bulbasaur. It's also worth noting that some of the shadow pokemon I started getting before this were a bit weird too. Like they would have double thunder punch unlocked before I'd open their heart at all. 

I can't give you my exact setting unfortunately since I accidentally deleted my copy of the randomizer while cleaning up files (believe me I've looked), but I can say for sure that I used release 1.1.5 and randomized my rom in December. I can provide the iso and save file if you'd like, I saved after Snattle but before the Ardos and Gorgan weirdness. 

Also, it's probably worth noting that the Battle CDs also seem to have experienced a similar issue, so that may be related.

**Comment by TheWrathAbove** [comment] 2022-05-15 18:27
I should note that I did use "force fully evolved by level 41" since I wanted to guarantee that all the pokemon I fought at the very end were fully evolved. I think that might have a part to play.

**Comment by rotobash** [comment] 2022-05-20 12:29
Hi there, thanks for reporting this. No worries about the missing setting file, your description is clear enough to troubleshoot with. 

That's interesting though... I'll have to take a closer look. I did fix some issues relating to evolutions since December but I'm not entirely sure if they would resolve this specifically. Just to clarify, you're saying the Battle CDs also have trainers with no Pokemon?

You might be right about the force fully evolved setting, this may have caused a problem in conjunction with the other issue I fixed earlier but it's hard to say. I'll report back after some more investigation and let you know if this is still an issue in the current version. Cheers.

**Comment by TheWrathAbove** [comment] 2022-05-21 05:48
Neither the player nor the enemy had pokemon, except for the first battle CD in which the player had a magikarp and the enemy had nothing. Additionally this also applied to the intro battle.

I'll also note that I randomized a fresh rom on the newest version using force fully evolved and it seemed to work fine. Although I'll note that Shadow Lugia randomized into a Cascoon despite being over the selected level for "force fully evolved". 

Speaking of that randomized rom I can also corroborate the issue that "no duplicate shadows" is bugged as Greevil started his fight with 2 shadow Grumpig.

**Comment by rotobash** [comment] 2022-05-26 03:48
So yea, took a look into it. I tried just the settings you mentioned (i.e. force fully evolved at 41) on the latest version and it looked okay to me. The battle CD trainers looked randomized as well. I'm hoping it was just an issue with that version, and it seems like it's working for you now which is good.

I checked the force fully evolved logic, and it looks like it only goes to the next stage of evolution rather than the last. Oops... I have a fix for this, but I also have a few other things I want to fix before making a release.

I can confirm the no duplicate shadows isn't working right but I have a fix for that as well.

**Closed** 2022-05-27 10:11 UTC
Labels: bug
